import SwiftUI

/// DualSense controller button definitions extracted from SVG
struct DualSenseButtonProvider: ControllerButtonProvider {
    // Matches DualSense_front.svg generated by scripts/extract_clean_views.py
    let viewBox = DualSenseVisuals.frontViewBox

    var buttons: [String: ControllerButton] {
        Self.buttonDefinitions
    }

    // MARK: - Button Definitions

    private static let buttonDefinitions: [String: ControllerButton] = {
        var buttons: [String: ControllerButton] = [:]
        guard
            let url = Bundle.module.url(
                forResource: DualSenseVisuals.frontResourceName,
                withExtension: "svg"
            )
        else {
            fatalError("Missing front SVG resource for button extraction")
        }

        let extractedPaths = SVGButtonExtractor.extract(url: url)

        func p(_ id: String) -> String {
            guard let path = extractedPaths[id] else {
                fatalError("Missing SVG path for button id: \(id)")
            }
            return path
        }

        // Face buttons
        buttons["triangle"] = .faceButton(
            id: "triangle", label: "△",
            path: p("triangle"),
            color: Color(red: 0.4, green: 0.8, blue: 0.6)
        )
        buttons["circle"] = .faceButton(
            id: "circle", label: "○",
            path: p("circle"),
            color: Color(red: 1.0, green: 0.4, blue: 0.4)
        )
        buttons["cross"] = .faceButton(
            id: "cross", label: "✕",
            path: p("cross"),
            color: Color(red: 0.5, green: 0.6, blue: 1.0)
        )
        buttons["square"] = .faceButton(
            id: "square", label: "□",
            path: p("square"),
            color: Color(red: 0.9, green: 0.5, blue: 0.7)
        )

        // D-pad
        buttons["dpad_up"] = .dpad(id: "dpad_up", label: "↑", path: p("dpad_up"))
        buttons["dpad_down"] = .dpad(id: "dpad_down", label: "↓", path: p("dpad_down"))
        buttons["dpad_left"] = .dpad(id: "dpad_left", label: "←", path: p("dpad_left"))
        buttons["dpad_right"] = .dpad(id: "dpad_right", label: "→", path: p("dpad_right"))

        // Analog sticks
        buttons["l3"] = .stick(id: "l3", label: "L3", path: p("l3"))
        buttons["r3"] = .stick(id: "r3", label: "R3", path: p("r3"))

        // Shoulder buttons
        buttons["l1"] = .shoulder(id: "l1", label: "L1", path: p("l1"))
        buttons["r1"] = .shoulder(id: "r1", label: "R1", path: p("r1"))
        buttons["l2"] = .trigger(id: "l2", label: "L2", path: p("l2"))
        buttons["r2"] = .trigger(id: "r2", label: "R2", path: p("r2"))

        // Center buttons (mute + lightbar are drawn in the SVG but not exposed by
        // GameController and the lightbar path overlaps touchpad — both are omitted
        // from the editor so users can't bind what won't fire.)
        buttons["share"] = .center(id: "share", label: "Share", path: p("share"))
        buttons["options"] = .center(id: "options", label: "Options", path: p("options"))
        buttons["ps"] = .center(id: "ps", label: "PS", path: p("ps"))
        buttons["touchpad"] = .center(id: "touchpad", label: "Touchpad", path: p("touchpad"))

        return buttons
    }()
}

// MARK: - Button Factory Extensions

private extension ControllerButton {
    static func faceButton(id: String, label: String, path: String, color: Color) -> ControllerButton {
        ControllerButton(id: id, pathData: path, label: label, color: color)
    }

    static func dpad(id: String, label: String, path: String) -> ControllerButton {
        ControllerButton(id: id, pathData: path, label: label, color: nil)
    }

    static func stick(id: String, label: String, path: String) -> ControllerButton {
        ControllerButton(id: id, pathData: path, label: label, color: nil)
    }

    static func shoulder(id: String, label: String, path: String) -> ControllerButton {
        ControllerButton(id: id, pathData: path, label: label, color: nil)
    }

    static func trigger(id: String, label: String, path: String) -> ControllerButton {
        ControllerButton(id: id, pathData: path, label: label, color: nil)
    }

    static func center(id: String, label: String, path: String) -> ControllerButton {
        ControllerButton(id: id, pathData: path, label: label, color: nil)
    }
}
